name: Publish Library
run-name: Publish Library ${{github.ref_name}}
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: false
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # ex. v2.0.0
      - "v[0-9]+.[0-9]+.[0-9]+-rc-[0-9]+" # ex. v2.1.0-rc-1

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      deployments: write
      statuses: write
      pull-requests: write
      packages: write
    steps:
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: "gradle"

      - name: Decode GPG key
        run: |
          echo "${{ secrets.GPG_SECRET_KEY_BASE64 }}" | base64 --decode > ./siwf/signing-secret-key.gpg

      - name: Check Step
        run: gradle check

      - name: Publish Dry Run
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME }}
          JRELEASER_MAVENCENTRAL_SONATYPE_TOKEN: ${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
        run: |
          gradle siwf:publishReleasePublicationToPreDeployRepository
          gradle siwf:jreleaserFullRelease
