name: Publish Library to Maven Central
run-name: Publish Release ${{github.ref_name}}
concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: false
on:
  push:
    branches:
      - 9-ci-initial-setup
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # ex. v2.0.0
      - "v[0-9]+.[0-9]+.[0-9]+-SNAPSHOT" # ex. v2.1.0-SNAPSHOT

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
      deployments: write
      statuses: write
      pull-requests: write
      packages: write
    env:
      RELEASE_VERSION: ${{github.ref_name}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: "temurin"

      - name: Decode GPG key
        run: |
          echo "${{ secrets.GPG_SECRET_KEY_BASE64 }}" | base64 --decode > ./siwf/signing-secret-key.gpg

      - name: Dry Run
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME }}
          JRELEASER_MAVENCENTRAL_SONATYPE_TOKEN: ${{ secrets.JRELEASER_MAVENCENTRAL_SONATYPE_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
        run: |
          ./gradlew siwf:publishReleasePublicationToPreDeployRepository
          ./gradlew siwf:jreleaserFullRelease --dryrun
